const { Schema, model } = require("mongoose");

const schema = Schema({
    guildID: String,
    prefix: { type: String, default: "/" },
    autorole: { type: String, default: "не установлена" },
    antilink: { type: Boolean, default: false },
    vxodchannel: { type: String, default: "Не указано" },
    logchannel: { type: String, default: "Не указано" },
    supportchannel: { type: String, default: "support" },
    reportschannel: { type: String, default: "reports-log" },
    numberticket: { type: Number, default: 0 },
    supportrole: [String],
    delpin: { type: Boolean, default: false },
    randomemoji: { type: Boolean, default: false },
    deleteMessage: { type: Boolean, default: false },
    prime: { type: Boolean, default: false },
    activeCategory: { type: String, default: "Active complaints" },
    holdCategory: { type: String, default: "Pending complaints" },
    closeCategory: { type: String, default: "Trash" },
    r_ad: { type: String, default: "Не указано" },
    ad_incoming: { type: String, default: "Не указано" },
    ad_outgoing: { type: String, default: "Не указано" },
    warns: { type: Number, default: 3 },
    warnPunish: { type: String, default: "kick" },
    language: { type: String, default: "Русский" },
    timeTicketDelete: { type: String, default: 86400000 },
    ignoreChannels: { type: [String] },
    modules: {
        ad: { type: Boolean, default: true },
        economy: { type: Boolean, default: true },
        fun: { type: Boolean, default: true },
        info: { type: Boolean, default: true },
        moderation: { type: Boolean, default: true },
        nsfw: { type: Boolean, default: true },
        ticket: { type: Boolean, default: true },
        user: { type: Boolean, default: true },
        embed: { type: Boolean, default: true }
    },
    commands: {
    accept: { type: Boolean, default: true },
    ad: { type: Boolean, default: true },
    deny: { type: Boolean, default: true},
    editad: { type: Boolean, default: true },
    addshop: { type: Boolean, default: true },
    editshop: { type: Boolean, default: true },
    shoplist: { type: Boolean, default: true },
    dellshop: { type: Boolean, default: true },
    buy: { type: Boolean, default: true },
    bonus: { type: Boolean, default: true },
    box: { type: Boolean, default: true },
    coinleaders: { type: Boolean, default: true },
    promoleaders: { type: Boolean, default: true },
    createpromocode: { type: Boolean, default: true },
    deletepromocode: { type: Boolean, default: true },
    fish: { type: Boolean, default: true },
    fullobnul: { type: Boolean, default: true },
    game: { type: Boolean, default: true },
    jobs: { type: Boolean, default: true },
    kn: { type: Boolean, default: true },
    mypromocode: { type: Boolean, default: true },
    pay: { type: Boolean, default: true },
    promocode: { type: Boolean, default: true },
    setmoney: { type: Boolean, default: true },
    inv: { type: Boolean, default: true },
    invput: { type: Boolean, default: true },
    invtake: { type: Boolean, default: true },
    try: { type: Boolean, default: true },
    work: { type: Boolean, default: true },
    works: { type: Boolean, default: true },
    ball: { type: Boolean, default: true },
    reverse: { type: Boolean, default: true },
    accinfo: { type: Boolean, default: true },
    serverinfo: { type: Boolean, default: true },
    newgame: { type: Boolean, default: true },
    link: { type: Boolean, default: true },
    ping: { type: Boolean, default: true },
    prime: { type: Boolean, default: true },
    profile: { type: Boolean, default: true },
    stats: { type: Boolean, default: true },
    vote: { type: Boolean, default: true },
    ban: { type: Boolean, default: true },
    chat: { type: Boolean, default: true },
    check: { type: Boolean, default: true },
    clear: { type: Boolean, default: true },
    edit: { type: Boolean, default: true },
    giverole: { type: Boolean, default: true },
    history: { type: Boolean, default: true },
    kick: { type: Boolean, default: true },
    msg: { type: Boolean, default: true },
    mute: { type: Boolean, default: true },
    myinfo: { type: Boolean, default: true },
    pin: { type: Boolean, default: true },
    removerole: { type: Boolean, default: true },
    setstat: { type: Boolean, default: true },
    unban: { type: Boolean, default: true },
    unmute: { type: Boolean, default: true },
    unpin: { type: Boolean, default: true },
    unwarn: { type: Boolean, default: true },
    warn: { type: Boolean, default: true },
    fourk: { type: Boolean, default: true },
    anal: { type: Boolean, default: true },
    ass: { type: Boolean, default: true },
    gif: { type: Boolean, default: true },
    gonewild: { type: Boolean, default: true },
    hanal: { type: Boolean, default: true },
    hass: { type: Boolean, default: true },
    hentai: { type: Boolean, default: true },
    hmidriff: { type: Boolean, default: true },
    holo: { type: Boolean, default: true },
    pussy: { type: Boolean, default: true },
    solo: { type: Boolean, default: true },
    thigh: { type: Boolean, default: true },
    active: { type: Boolean, default: true },
    hold: { type: Boolean, default: true },
    close: { type: Boolean, default: true },
    blocksupport: { type: Boolean, default: true },
    removeblocksupport: { type: Boolean, default: true },
    avatar: { type: Boolean, default: true },
    embsetup: { type: Boolean, default: true },
    embfield: { type: Boolean, default: true },
    embsend: { type: Boolean, default: true },
    embclear: { type: Boolean, default: true },
    user: { type: Boolean, default: true }
    },
    embed: {
        color: { type: String, default: "не указано" },
        title: { type: String, default: "не указано" },
        description: { type: String, default: "не указано" },
        timestamp: { type: String, default: "не указано" },
        image: { type: String, default: "не указано" },
        footer: { type: String, default: "не указано" },
        footerImage: { type: String, default: "не указано" },
        author: { type: String, default: "не указано" },
        authorImage: { type: String, default: "не указано" },
    },
    efield: {
        setembed_fields_zero: { type: String, default: "нет" },
        setembed_fields_one: { type: String, default: "нет" },
        setembed_fields_two: { type: String, default: "нет" },
        setembed_fields_three: { type: String, default: "нет" },
        setembed_fields_four: { type: String, default: "нет" },
        setembed_fields_five: { type: String, default: "нет" },
        setembed_fields_six: { type: String, default: "нет" },
        setembed_fields_seven: { type: String, default: "нет" },
        setembed_fields_eigth: { type: String, default: "нет" },
        setembed_fields_nine: { type: String, default: "нет" }
    },
    channels: {
        roleCreate: { type: String, default: "не указано" },
        roleUpdate: { type: String, default: "не указано" },
        roleDelete: { type: String, default: "не указано" },
        channelCreate: { type: String, default: "не указано" },
        channelUpdate: { type: String, default: "не указано" },
        channelDelete: { type: String, default: "не указано" },
        guildBanAdd: { type: String, default: "не указано" },
        guildBanRemove: { type: String, default: "не указано" },
        guildUpdate: { type: String, default: "не указано" },
        stickerCreate: { type: String, default: "не указано" },
        stickerUpdate: { type: String, default: "не указано" },
        stickerDelete: { type: String, default: "не указано" }
    }
});

module.exports = model("Guild", schema)
